// GDS Graph Projections for Software Engineering
// Generated by create-context-graph
// Note: Requires Neo4j GDS plugin (AuraDS or Enterprise + GDS)

// Full entity projection (all node labels and relationship types)
CALL gds.graph.project(
  'software_engineering_full',
  ['Person', 'Organization', 'Location', 'Event', 'Object', 'Repository', 'Issue', 'PullRequest', 'Deployment', 'Service', 'Incident'],
  ['WORKS_FOR', 'LOCATED_AT', 'PARTICIPATED_IN', 'AUTHORED', 'REVIEWED', 'ASSIGNED_TO', 'FILED_BY', 'BELONGS_TO', 'TARGETS', 'FIXES', 'DEPLOYED_TO', 'TRIGGERED_BY', 'DEPENDS_ON', 'CAUSED_INCIDENT', 'AFFECTED', 'ON_CALL', 'CONTAINS']
);

// Community detection
CALL gds.louvain.write('software_engineering_full', {
  writeProperty: 'community'
});

// PageRank centrality
CALL gds.pageRank.write('software_engineering_full', {
  writeProperty: 'pagerank'
});

// FastRP embeddings for structural similarity
CALL gds.fastRP.write('software_engineering_full', {
  embeddingDimension: 128,
  writeProperty: 'fastrp_embedding'
});

// Clean up projection
CALL gds.graph.drop('software_engineering_full');
