/**
 * Domain configuration for Software Engineering
 * Generated by create-context-graph
 */

export const DOMAIN = {
  id: "software-engineering",
  name: "Software Engineering",
  description: "Software development lifecycle, repositories, issues, deployments, and team collaboration",
  tagline: "AI-powered Software Intelligence",
};

export const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api";

/**
 * Returns headers to include on every backend API call.
 * NEXT_PUBLIC_BASIC_AUTH = base64(user:pass) — set when BASIC_AUTH is enabled.
 * Generate: python3 -c "import base64; print(base64.b64encode(b'user:pass').decode())"
 */
export function apiHeaders(extra?: Record<string, string>): Record<string, string> {
  const auth   = process.env.NEXT_PUBLIC_BASIC_AUTH;
  const apiKey = process.env.NEXT_PUBLIC_BACKEND_API_KEY;
  return {
    ...(auth   ? { Authorization: `Basic ${auth}` } : {}),
    ...(apiKey ? { "X-Api-Key": apiKey }            : {}),
    ...extra,
  };
}

export const NODE_COLORS: Record<string, string> = {"Deployment": "#f59e0b", "Event": "#f97316", "Incident": "#dc2626", "Issue": "#ef4444", "Location": "#a855f7", "Object": "#eab308", "Organization": "#3b82f6", "Person": "#22c55e", "PullRequest": "#14b8a6", "Repository": "#6366f1", "Service": "#0ea5e9"};

export const NODE_SIZES: Record<string, number> = {"Deployment": 15, "Event": 20, "Incident": 25, "Issue": 15, "Location": 20, "Object": 20, "Organization": 20, "Person": 20, "PullRequest": 15, "Repository": 25, "Service": 30};

export const DEFAULT_CYPHER = `MATCH (s:Service)-[r:DEPENDS_ON]-(other:Service) RETURN s, r, other LIMIT 100`;

export const SCHEMA_NODE_SIZE = 30;
export const SCHEMA_REL_COLOR = "#94a3b8";

export interface GraphData {
  results: Record<string, unknown>[];
}

export interface DemoScenario {
  name: string;
  prompts: string[];
}

export const DEMO_SCENARIOS: DemoScenario[] = [{"name": "Code Review \u0026 PRs", "prompts": ["Show me all open pull requests across our repositories", "Who are the most active code reviewers this sprint?", "What issues are blocked or in review right now?"]}, {"name": "Incident Response", "prompts": ["Are there any active incidents? What services are affected?", "Show me the deployment history for the auth service this week", "What was the root cause of the last sev1 incident?"]}, {"name": "Engineering Intelligence", "prompts": ["Which services have the most dependencies?", "What\u0027s the relationship between recent deployments and incidents?", "Find similar past incidents to a current database performance issue"]}];
